
package com.etz.nipinward.soapws.nibss.tsq;

import com.etz.nipinward.xsd.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NIPTSQInterface", targetNamespace = "http://core.nip.nibss/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NIPTSQInterface {


    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "txnstatusquerysingleitem", targetNamespace = "http://core.nip.nibss/", className = "nibss.nip.tsqcore.Txnstatusquerysingleitem")
    @ResponseWrapper(localName = "txnstatusquerysingleitemResponse", targetNamespace = "http://core.nip.nibss/", className = "nibss.nip.tsqcore.TxnstatusquerysingleitemResponse")
    @Action(input = "http://core.nip.nibss/NIPTSQInterface/txnstatusquerysingleitemRequest", output = "http://core.nip.nibss/NIPTSQInterface/txnstatusquerysingleitemResponse")
    public String txnstatusquerysingleitem(
            @WebParam(name = "request", targetNamespace = "")
                    String request);

}
