//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.13 at 09:21:24 PM WAT 
//


package com.etz.nipinward.xsd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.assets.banknipinboundservice.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.assets.banknipinboundservice.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NameenquirysingleitemRequest }
     * 
     */
    public NameenquirysingleitemRequest createNameenquirysingleitemRequest() {
        return new NameenquirysingleitemRequest();
    }

    /**
     * Create an instance of {@link NameenquirysingleitemResponse }
     * 
     */
    public NameenquirysingleitemResponse createNameenquirysingleitemResponse() {
        return new NameenquirysingleitemResponse();
    }

    /**
     * Create an instance of {@link FundtransfersingleitemDcRequest }
     * 
     */
    public FundtransfersingleitemDcRequest createFundtransfersingleitemDcRequest() {
        return new FundtransfersingleitemDcRequest();
    }

    /**
     * Create an instance of {@link FundtransfersingleitemDcResponse }
     * 
     */
    public FundtransfersingleitemDcResponse createFundtransfersingleitemDcResponse() {
        return new FundtransfersingleitemDcResponse();
    }

    /**
     * Create an instance of {@link FundtransfersingleitemDdRequest }
     * 
     */
    public FundtransfersingleitemDdRequest createFundtransfersingleitemDdRequest() {
        return new FundtransfersingleitemDdRequest();
    }

    /**
     * Create an instance of {@link FundtransfersingleitemDdResponse }
     * 
     */
    public FundtransfersingleitemDdResponse createFundtransfersingleitemDdResponse() {
        return new FundtransfersingleitemDdResponse();
    }

    /**
     * Create an instance of {@link BalanceenquiryRequest }
     * 
     */
    public BalanceenquiryRequest createBalanceenquiryRequest() {
        return new BalanceenquiryRequest();
    }

    /**
     * Create an instance of {@link BalanceenquiryResponse }
     * 
     */
    public BalanceenquiryResponse createBalanceenquiryResponse() {
        return new BalanceenquiryResponse();
    }

    /**
     * Create an instance of {@link FundtransferAdviceDcRequest }
     * 
     */
    public FundtransferAdviceDcRequest createFundtransferAdviceDcRequest() {
        return new FundtransferAdviceDcRequest();
    }

    /**
     * Create an instance of {@link FundtransferAdviceDcResponse }
     * 
     */
    public FundtransferAdviceDcResponse createFundtransferAdviceDcResponse() {
        return new FundtransferAdviceDcResponse();
    }

    /**
     * Create an instance of {@link FundtransferAdviceDdRequest }
     * 
     */
    public FundtransferAdviceDdRequest createFundtransferAdviceDdRequest() {
        return new FundtransferAdviceDdRequest();
    }

    /**
     * Create an instance of {@link FundtransferAdviceDdResponse }
     * 
     */
    public FundtransferAdviceDdResponse createFundtransferAdviceDdResponse() {
        return new FundtransferAdviceDdResponse();
    }

    /**
     * Create an instance of {@link AmountblockRequest }
     * 
     */
    public AmountblockRequest createAmountblockRequest() {
        return new AmountblockRequest();
    }

    /**
     * Create an instance of {@link AmountblockResponse }
     * 
     */
    public AmountblockResponse createAmountblockResponse() {
        return new AmountblockResponse();
    }

    /**
     * Create an instance of {@link AmountUnblockRequest }
     * 
     */
    public AmountUnblockRequest createAmountUnblockRequest() {
        return new AmountUnblockRequest();
    }

    /**
     * Create an instance of {@link AmountUnblockResponse }
     * 
     */
    public AmountUnblockResponse createAmountUnblockResponse() {
        return new AmountUnblockResponse();
    }

    /**
     * Create an instance of {@link AccountblockRequest }
     * 
     */
    public AccountblockRequest createAccountblockRequest() {
        return new AccountblockRequest();
    }

    /**
     * Create an instance of {@link AccountblockResponse }
     * 
     */
    public AccountblockResponse createAccountblockResponse() {
        return new AccountblockResponse();
    }

    /**
     * Create an instance of {@link AccountUnblockRequest }
     * 
     */
    public AccountUnblockRequest createAccountUnblockRequest() {
        return new AccountUnblockRequest();
    }

    /**
     * Create an instance of {@link AccountUnblockResponse }
     * 
     */
    public AccountUnblockResponse createAccountUnblockResponse() {
        return new AccountUnblockResponse();
    }

    /**
     * Create an instance of {@link FinancialinstitutionlistRequest }
     * 
     */
    public FinancialinstitutionlistRequest createFinancialinstitutionlistRequest() {
        return new FinancialinstitutionlistRequest();
    }

    /**
     * Create an instance of {@link FinancialinstitutionlistResponse }
     * 
     */
    public FinancialinstitutionlistResponse createFinancialinstitutionlistResponse() {
        return new FinancialinstitutionlistResponse();
    }

    /**
     * Create an instance of {@link MandateadviceRequest }
     * 
     */
    public MandateadviceRequest createMandateadviceRequest() {
        return new MandateadviceRequest();
    }

    /**
     * Create an instance of {@link MandateadviceResponse }
     * 
     */
    public MandateadviceResponse createMandateadviceResponse() {
        return new MandateadviceResponse();
    }

    /**
     * Create an instance of {@link FtackcreditrequestRequest }
     * 
     */
    public FtackcreditrequestRequest createFtackcreditrequestRequest() {
        return new FtackcreditrequestRequest();
    }

    /**
     * Create an instance of {@link FtackcreditrequestResponse }
     * 
     */
    public FtackcreditrequestResponse createFtackcreditrequestResponse() {
        return new FtackcreditrequestResponse();
    }

}
